CREATE TABLE user_table(
    uid VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone BIGINT NOT NULL UNIQUE,
    email VARCHAR(200) UNIQUE,
    handle VARCHAR(50) NOT NULL UNIQUE,
    bio VARCHAR(100),
    is_verified BOOLEAN DEFAULT FALSE,
    is_public BOOLEAN DEFAULT TRUE
)

CREATE TABLE post( pid VARCHAR(255) PRIMARY KEY, uid VARCHAR(255) NOT NULL, postImage VARCHAR(255), caption VARCHAR (255), createDate DATETIME )
